### ISSUE TITLE
json_pure 2.7.4 breaks uaac

### ISSUE THREAD

**Issue by MiliDurasovic** [cloudfoundry/cf-uaac#136] opened 2024-10-28 10:17 UTC
Since json_pure version `2.7.4` I receive the following error while setting the target:
```
uaac --skip-ssl-validation  target https://uaa."${api}" -t
...
wrong number of arguments (given 2, expected 1)
```

Afterwards `.uaac.yml` is simply empty:
```
# cat ~/.uaac.yml
--- {}
```

After rolling back to json_pure version `2.7.2`, uaac works again without any issues.

Maybe consider strictly pinning to json_pure `2.7.2` until the issue has been identified and resolved?

**Comment by CFMCGEE** [comment] 2024-10-29 20:49
I'm experiencing this exact issue starting today... 

Which version of CF-MGMT are you using @MiliDurasovic?

**Comment by jensdaseking** [comment] 2024-10-30 06:42
Our workaround:

```
gem install cf-uaac
gem uninstall json_pure --all --force
gem install json_pure --version 2.7.2
```

**Comment by MiliDurasovic** [comment] 2024-10-30 07:12
@CFMCGEE I´m not using cf-mgmt and I don´t think it matters for this issue.

---

@jensdaseking 
We applied this workaround also in our docker images.

```
gem install cf-uaac
gem uninstall json_pure -aIx
gem install json_pure -v 2.7.2
```

**Comment by strehle** [comment] 2024-10-30 08:50
hi,

for now you can use the workaround. there are multiple json libraries in use which cause the problem, e.g. https://github.com/ruby/json/issues/646

Will cleanup here but first in https://github.com/cloudfoundry/cf-uaa-lib/pull/95

**Comment by CFMCGEE** [comment] 2024-10-30 13:29
@MiliDurasovic - Apologizes, I meant UAAC CLI. I'll try the work around provided. Thanks for raising this issue!

**Comment by strehle** [comment] 2024-10-30 16:02
@MiliDurasovic heads up: please check if with https://github.com/ruby/json/releases/tag/v2.7.5 the issue is fixed ? because changelog seems to show this.

However there will be a cleanup and only one json library will be initialized in future

**Comment by MiliDurasovic** [comment] 2024-10-30 17:11
@strehle Thank you. 
I can confirm that the issue is gone for me with https://github.com/ruby/json/releases/tag/v2.7.5 .

**Comment by CFMCGEE** [comment] 2024-10-30 18:04
@strehle Thanks! Works for me now as well.

**Comment by MiliDurasovic** [comment] 2024-11-01 09:25
@strehle Since tonight we suddenly receive another error:
```
+ uaac --skip-ssl-validation target https://uaa."${api}"

<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- multi_json (LoadError)

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'

	from /var/lib/gems/3.0.0/gems/cf-uaac-4.21.0/lib/uaa/stub/server.rb:19:in `<top (required)>'

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'

	from /var/lib/gems/3.0.0/gems/cf-uaac-4.21.0/lib/uaa/cli/token.rb:17:in `<top (required)>'

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'

	from /var/lib/gems/3.0.0/gems/cf-uaac-4.21.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'

	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Looks like the removal of multi_json is the cause:
https://github.com/cloudfoundry/cf-uaa-lib/pull/95

**Comment by strehle** [comment] 2024-11-01 11:14
see https://github.com/cloudfoundry/cf-uaa-lib/releases/tag/v4.0.6

Sorry for breaking it. Will do replacement in several steps, but we want remove this library and replace it with json / json_pure only

**Closed** 2024-11-01 17:36 UTC
